{
 "title": "Free York Pool Dashboard (Public)",
 "description": "Free York Pool Monitor",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Epoch",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_epoch_int{alias=\"core\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Current Epoch Progress",
   "type": "bargauge",
   "description": "Slot height in current epoch (taken from Core node)",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_slotInEpoch_int{alias=\"core\"}/432000 ",
     "legendFormat": "{{none}}"
    }
   ]
  },
  {
   "title": "Remaining KES Periods",
   "type": "bargauge",
   "description": "Remaining KES periods before we need to rotate keys",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_remainingKESPeriods_int{alias=\"core\"}",
     "legendFormat": "{{none}}"
    }
   ]
  },
  {
   "title": "Peers (Core)",
   "type": "stat",
   "description": "Connected peers to/from Core Node",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_connectedPeers_int{alias=\"core\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Peers (Relay1)",
   "type": "stat",
   "description": "Connected peers to/from Relay 1",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_connectedPeers_int{alias=\"relay1\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Peers (Relay2)",
   "type": "stat",
   "description": "Connected peers to/from Relay 2",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_connectedPeers_int{alias=\"relay2\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Core TX's processed",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_txsProcessedNum_int{alias=\"core\"}",
     "legendFormat": "Core"
    }
   ]
  },
  {
   "title": "Relay1 TX's processed",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_txsProcessedNum_int{alias=\"relay1\"}",
     "legendFormat": "Relay1"
    }
   ]
  },
  {
   "title": "Relay2 TX's processed",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_txsProcessedNum_int{alias=\"relay2\"}",
     "legendFormat": "Relay2"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Core node uptime",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(time() - node_boot_time_seconds{alias=\"core\"})",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Relay node 1 uptime",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(time() - node_boot_time_seconds{alias=\"relay1\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Relay node 2 uptime",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(time() - node_boot_time_seconds{alias=\"relay2\"})"
    }
   ]
  },
  {
   "title": "Chain Density",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_density_real * 100",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Block height",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_blockNum_int{alias=\"core\"}",
     "legendFormat": "core"
    },
    {
     "expr": "cardano_node_metrics_blockNum_int{alias=\"relay1\"}",
     "legendFormat": "relay1"
    },
    {
     "expr": "cardano_node_metrics_blockNum_int{alias=\"relay2\"}",
     "legendFormat": "relay2"
    }
   ]
  },
  {
   "title": "Slot Height",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_slotNum_int{alias=\"core\"}",
     "legendFormat": "core"
    },
    {
     "expr": "cardano_node_metrics_slotNum_int{alias=\"relay1\"}",
     "legendFormat": "relay1"
    },
    {
     "expr": "cardano_node_metrics_slotNum_int{alias=\"relay2\"}",
     "legendFormat": "relay2"
    }
   ]
  },
  {
   "title": "System Load (core node)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "%", "label": "Load" }
   ],
   "targets": [
    {
     "expr": "node_load1{alias=\"core\"}*100",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5{alias=\"core\"}*100",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load15{alias=\"core\"}*100",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "System Load (Relay 1)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "%", "label": "Load" }
   ],
   "targets": [
    {
     "expr": "node_load1{alias=\"relay1\"}*100",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5{alias=\"relay1\"}*100",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load15{alias=\"relay1\"}*100",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "System Load (Relay 2)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "%", "label": "Load" }
   ],
   "targets": [
    {
     "expr": "node_load1{alias=\"relay2\"}*100",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5{alias=\"relay2\"}*100",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load15{alias=\"relay2\"}*100",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "Time Synchronization (Core)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "s", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "node_timex_estimated_error_seconds{alias=\"core\"}",
     "legendFormat": "Est. error(s)"
    },
    {
     "expr": "node_timex_offset_seconds{alias=\"core\"}",
     "legendFormat": "Offset: Node vs. Ref."
    },
    {
     "expr": "node_timex_maxerror_seconds{alias=\"core\"}",
     "legendFormat": "Max. Error (s)"
    }
   ]
  },
  {
   "title": "Time Synchronization (Relay 1)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "s", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "node_timex_estimated_error_seconds{alias=\"relay1\"}",
     "legendFormat": "Est. error(s)"
    },
    {
     "expr": "node_timex_offset_seconds{alias=\"relay1\"}",
     "legendFormat": "Offset: Node vs. Ref."
    },
    {
     "expr": "node_timex_maxerror_seconds{alias=\"relay1\"}",
     "legendFormat": "Max. Error (s)"
    }
   ]
  },
  {
   "title": "Time Synchronization (Relay 2)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "s", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "node_timex_estimated_error_seconds{alias=\"relay2\"}",
     "legendFormat": "Est. error(s)"
    },
    {
     "expr": "node_timex_offset_seconds{alias=\"relay2\"}",
     "legendFormat": "Offset: Node vs. Ref."
    },
    {
     "expr": "node_timex_maxerror_seconds{alias=\"relay2\"}",
     "legendFormat": "Max. Error (s)"
    }
   ]
  },
  {
   "title": "Connected Peers (Core Node)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_connectedPeers_int{alias=\"core\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Connected Peers (Relay 1)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_connectedPeers_int{alias=\"relay1\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Connected Peers (Relay 2)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_connectedPeers_int{alias=\"relay2\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Core node block sync speed (blocks / min)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate (cardano_node_metrics_blockNum_int{alias=\"core\"}[150s]) *60",
     "legendFormat": "Core"
    }
   ]
  },
  {
   "title": "Relay1 node block sync speed (blocks / min)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 37 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate (cardano_node_metrics_blockNum_int{alias=\"relay1\"}[150s]) *60",
     "legendFormat": "Relay1"
    }
   ]
  },
  {
   "title": "Relay2 node block sync speed (blocks / min)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 37 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate (cardano_node_metrics_blockNum_int{alias=\"relay2\"}[150s]) *60",
     "legendFormat": "Relay2"
    }
   ]
  },
  {
   "title": "Core Node peak memory allocated",
   "type": "graph",
   "description": "Counts only memory that is physically free (from OS, in MBytes)",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "rts_gc_peak_megabytes_allocated{alias=\"core\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Relay1 peak memory allocated",
   "type": "graph",
   "description": "Counts only memory that is physically free (from OS, in MBytes)",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 43 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "rts_gc_peak_megabytes_allocated{alias=\"relay1\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Relay2 peak memory allocated",
   "type": "graph",
   "description": "Counts only memory that is physically free (from OS, in MBytes)",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 43 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "rts_gc_peak_megabytes_allocated{alias=\"relay2\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Mempool Transactions (Core Node)",
   "type": "graph",
   "description": "current",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "tx" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_txsInMempool_int{alias=\"core\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Mempool Transactions (Relay 1)",
   "type": "graph",
   "description": "current",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 48 },
   "yaxes": [
    { "format": "tx" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_txsInMempool_int{alias=\"relay1\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Mempool Transactions (Relay 2)",
   "type": "graph",
   "description": "current",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 48 },
   "yaxes": [
    { "format": "tx" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_txsInMempool_int{alias=\"relay2\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Core Node current \"residency\" (amount of live data)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "rts_gc_current_bytes_used{alias=\"core\"}/(1024*1024)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Relay1 current \"residency\" (amount of live data)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 53 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "rts_gc_current_bytes_used{alias=\"relay1\"}/(1024*1024)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Relay2 current \"residency\" (amount of live data)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 53 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "rts_gc_current_bytes_used{alias=\"relay2\"}/(1024*1024)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Core Node Aggregate Data Transfer",
   "type": "graph",
   "description": "1 hour rolling window",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{alias=\"core\"}[1h])) * 3600",
     "legendFormat": "Core"
    }
   ]
  },
  {
   "title": "Relay1 Aggregate Data Transfer",
   "type": "graph",
   "description": "1 hour rolling window",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 58 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{alias=\"relay1\"}[1h])) * 3600",
     "legendFormat": "relay1"
    }
   ]
  },
  {
   "title": "Relay2 Aggregate Data Transfer",
   "type": "graph",
   "description": "1 hour rolling window",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 58 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{alias=\"relay2\"}[1h])) * 3600",
     "legendFormat": "relay2"
    }
   ]
  },
  {
   "title": "Core Node max \"residency\"",
   "type": "graph",
   "description": "Amount of live data, MBytes",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "rts_gc_max_bytes_used{alias=\"core\"} /(1024*1024)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Relay1 max \"residency\"",
   "type": "graph",
   "description": "Amount of live data, MBytes",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 63 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "rts_gc_max_bytes_used{alias=\"relay1\"} /(1024*1024)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Relay2 max \"residency\"",
   "type": "graph",
   "description": "Amount of live data, MBytes",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 63 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "rts_gc_max_bytes_used{alias=\"relay2\"} /(1024*1024)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Core Node File Descriptors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_filefd_allocated{alias=\"core\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Relay1 File Descriptors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 68 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_filefd_allocated{alias=\"relay1\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Relay2 File Descriptors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 68 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_filefd_allocated{alias=\"relay2\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  }
 ]
}